/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package PropertiClient;

import PropertiRMI.OperationRMI;
import java.net.MalformedURLException;
import java.rmi.Naming;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.rmi.registry.LocateRegistry;
import java.rmi.registry.Registry;
import javax.swing.JOptionPane;
import PropertiRMI.Services;
import java.util.HashMap;
import java.util.Map;

/**
 *
 * @author ASUS
 */
public class SewaProperti extends javax.swing.JFrame {
        private double hargaDasar;
        private int luasProperti;
        private String lokasi;
        private String fasilitas;
        private String keamanan;

    /**
     * Creates new form SewaProperti
     */

    OperationRMI calc;

   public SewaProperti() throws RemoteException, NotBoundException, MalformedURLException {
        initComponents();
        try {
            Registry register = LocateRegistry.getRegistry("172.125.2.212"); //note : ganti dengan IP PC Server
            calc = (OperationRMI) Naming.lookup("rmi://172.125.2.212:2000/services");
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Tidak dapat terhubung ke server. Pastikan server RMI berjalan.");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        HargaDasar = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Lokasi = new javax.swing.JComboBox<>();
        LuasProperti = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        FasilitasBasic = new javax.swing.JRadioButton();
        FasilitasIntermediet = new javax.swing.JRadioButton();
        FasilitasPremium = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        Sedang = new javax.swing.JRadioButton();
        Tinggi = new javax.swing.JRadioButton();
        HargaSewaButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Total = new javax.swing.JTextPane();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 255, 102));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Rockwell Condensed", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 102, 255));
        jLabel1.setText("Perhitungan Harga Sewa Properti per Bulan");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Harga Dasar");

        HargaDasar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HargaDasarActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Luas Properti");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Lokasi");

        Lokasi.setBackground(new java.awt.Color(255, 255, 204));
        Lokasi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih", "Pusat Bisnis", "Pinggir Kota", "Perumahan" }));
        Lokasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LokasiActionPerformed(evt);
            }
        });

        LuasProperti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LuasPropertiActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Fasilitas");

        FasilitasBasic.setText("Basic");
        FasilitasBasic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FasilitasBasicActionPerformed(evt);
            }
        });

        FasilitasIntermediet.setText("Intermediet");
        FasilitasIntermediet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FasilitasIntermedietActionPerformed(evt);
            }
        });

        FasilitasPremium.setText("Premium");
        FasilitasPremium.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FasilitasPremiumActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Keamanan dan Aksesibilitas");

        Sedang.setText("Sedang");
        Sedang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SedangActionPerformed(evt);
            }
        });

        Tinggi.setText("Tinggi");
        Tinggi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TinggiActionPerformed(evt);
            }
        });

        HargaSewaButton.setBackground(new java.awt.Color(255, 153, 51));
        HargaSewaButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        HargaSewaButton.setText("Harga Sewa");
        HargaSewaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HargaSewaButtonActionPerformed(evt);
            }
        });

        Total.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                TotalAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane1.setViewportView(Total);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel7.setText("*Keterangan Fasilitas");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel8.setText("- Basic : Kamar Tidur, Kamar Mandi, Dapur, Listrik dan Air");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel9.setText("- Intermediet : Fasilitas Basic + AC, Parkiran, Ruang Tamu, Ruang Makan, ");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel10.setText("Penyimpanan, Pengelolah Sampah");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel11.setText("- Premium : Fasilitas Intermediet + Kolam Renang, Gym, Wi-Fi, Laundry,");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel12.setText("Layanan Kebersihan,  Area Bermain");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setText("/m²");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setText("m²");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(HargaSewaButton)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))
                                .addGap(45, 45, 45)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(HargaDasar, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(24, 24, 24)
                                        .addComponent(jLabel13))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(LuasProperti, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(24, 24, 24)
                                        .addComponent(jLabel14))
                                    .addComponent(FasilitasIntermediet)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(FasilitasBasic)
                                            .addComponent(Sedang))
                                        .addGap(76, 76, 76)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Tinggi)
                                            .addComponent(FasilitasPremium)))
                                    .addComponent(Lokasi, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane1)))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel11)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel12)
                                            .addComponent(jLabel10))))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(HargaDasar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(LuasProperti, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(Lokasi, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(FasilitasBasic)
                    .addComponent(FasilitasPremium))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FasilitasIntermediet)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Tinggi)
                    .addComponent(Sedang))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HargaSewaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FasilitasBasicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FasilitasBasicActionPerformed
        // TODO add your handling code here:
        // Mengatur pengali harga untuk fasilitas basic
        if(FasilitasBasic.isSelected()){
            FasilitasIntermediet.setSelected(false);
            FasilitasPremium.setSelected(false); 
        }
        
    }//GEN-LAST:event_FasilitasBasicActionPerformed

    private void HargaDasarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HargaDasarActionPerformed
        // TODO add your handling code here:
        try {
            hargaDasar = Double.parseDouble(HargaDasar.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Masukkan angka valid untuk harga dasar!");
        }
    }//GEN-LAST:event_HargaDasarActionPerformed

    private void LuasPropertiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LuasPropertiActionPerformed
        // TODO add your handling code here:
        try {
            luasProperti = Integer.parseInt(LuasProperti.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Masukkan angka valid untuk luas properti!");
        }
    }//GEN-LAST:event_LuasPropertiActionPerformed

    private void LokasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LokasiActionPerformed
        // TODO add your handling code here:
         lokasi = Lokasi.getSelectedItem().toString();
    }//GEN-LAST:event_LokasiActionPerformed

    private void FasilitasIntermedietActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FasilitasIntermedietActionPerformed
        // TODO add your handling code here:
        if(FasilitasIntermediet.isSelected()){
            FasilitasBasic.setSelected(false);
            FasilitasPremium.setSelected(false); 
        }
    }//GEN-LAST:event_FasilitasIntermedietActionPerformed

    private void FasilitasPremiumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FasilitasPremiumActionPerformed
        // TODO add your handling code here:
        if(FasilitasPremium.isSelected()){
            FasilitasIntermediet.setSelected(false);
            FasilitasBasic.setSelected(false); 
        }
    }//GEN-LAST:event_FasilitasPremiumActionPerformed

    private void SedangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SedangActionPerformed
        // TODO add your handling code here:
      // keamanan = true; 
        if(Sedang.isSelected()){
           Tinggi.setSelected(false);
        }
    }//GEN-LAST:event_SedangActionPerformed

    private void TinggiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TinggiActionPerformed
        // TODO add your handling code here:
        // keamanan = true; 
        if(Tinggi.isSelected()){
           Sedang.setSelected(false);
        }
    }//GEN-LAST:event_TinggiActionPerformed

    private void HargaSewaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HargaSewaButtonActionPerformed
        // TODO add your handling code here:
        // Validasi input dan penghitungan harga sewa properti
        try {
            // Validasi Harga Dasar
            double hargaDasar = Double.parseDouble(HargaDasar.getText());
            if (hargaDasar <= 0) {
                JOptionPane.showMessageDialog(this, "Harga Dasar harus lebih dari 0!");
                return;
            }

            // Validasi Luas Properti
            int luasProperti = Integer.parseInt(LuasProperti.getText());
            if (luasProperti <= 0) {
                JOptionPane.showMessageDialog(this, "Luas Properti harus lebih dari 0!");
                return;
            }

            // Lokasi
            String lokasiDipilih = Lokasi.getSelectedItem().toString();
            if (lokasiDipilih.equals("Item 1")) {
                JOptionPane.showMessageDialog(this, "Pilih lokasi yang valid!");
                return;
            }

            String lokasi = ""; // Lokasi yang sesuai dengan server
            switch (lokasiDipilih) {
                case "Pusat Bisnis":
                    lokasi = "pusat bisnis";
                    break;
                case "Pinggir Kota":
                    lokasi = "pinggiran kota";
                    break;
                case "Perumahan":
                    lokasi = "perumahan";
                    break;
                default:
                    JOptionPane.showMessageDialog(this, "Lokasi tidak valid!");
                    return;
            }

            // Fasilitas
            String fasilitas = "";
            if (FasilitasBasic.isSelected()) {
                fasilitas = "basic";
            } else if (FasilitasIntermediet.isSelected()) {
                fasilitas = "intermediate";
            } else if (FasilitasPremium.isSelected()) {
                fasilitas = "premium";
            } else {
                JOptionPane.showMessageDialog(this, "Pilih salah satu jenis fasilitas!");
                return;
            }

            // Keamanan
//            boolean keamanan = false;
//            if (Sedang.isSelected()) {
//                keamanan = true;
//            } else if (!Tinggi.isSelected()) {
//                JOptionPane.showMessageDialog(this, "Pilih tingkat keamanan!");
//                return;
//            }

            String keamanan = "";
            if (Sedang.isSelected()) {
                keamanan = "sedang";
            } else if (Tinggi.isSelected()) {
                keamanan = "tinggi";
            } else {
                JOptionPane.showMessageDialog(this, "Pilih salah satu jenis Keamanan!");
                return;
            }

            // Menghitung harga sewa menggunakan RMI
            double totalHargaSewa = calc.calculateRent(hargaDasar, luasProperti, lokasi, fasilitas, keamanan);

            // Menampilkan hasil pada field Total
            Total.setText(String.format("Rp %.2f", totalHargaSewa));

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Masukkan angka yang valid untuk Harga Dasar dan Luas Properti!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal menghitung harga sewa: " + e.getMessage());
        }
    }//GEN-LAST:event_HargaSewaButtonActionPerformed

    private void TotalAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_TotalAncestorAdded
        // TODO add your handling code here:
        Total.setText("Rp. "); 
        Total.setEditable(false);
    }//GEN-LAST:event_TotalAncestorAdded

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            // Menjalankan aplikasi GUI
            new SewaProperti().setVisible(true);
        } catch (RemoteException | NotBoundException | MalformedURLException e) {
            // Menangani exception yang mungkin terjadi saat inisialisasi RMI
            e.printStackTrace();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton FasilitasBasic;
    private javax.swing.JRadioButton FasilitasIntermediet;
    private javax.swing.JRadioButton FasilitasPremium;
    private javax.swing.JTextField HargaDasar;
    private javax.swing.JButton HargaSewaButton;
    private javax.swing.JComboBox<String> Lokasi;
    private javax.swing.JTextField LuasProperti;
    private javax.swing.JRadioButton Sedang;
    private javax.swing.JRadioButton Tinggi;
    private javax.swing.JTextPane Total;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
